/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#fbf9f4",
        "surface-dim": "#dbdad5",
        "surface-bright": "#fbf9f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "surface-container": "#f0eee9",
        "surface-container-high": "#eae8e3",
        "surface-container-highest": "#e4e2dd",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#424844",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f1ec",
        outline: "#727973",
        "outline-variant": "#c2c8c2",
        "surface-tint": "#496455",
        primary: "#173124",
        "on-primary": "#ffffff",
        "primary-container": "#2d4739",
        "on-primary-container": "#98b5a3",
        "inverse-primary": "#b0cdbb",
        secondary: "#795900",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffc641",
        "on-secondary-container": "#715300",
        tertiary: "#501a08",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6c301c",
        "on-tertiary-container": "#ee987e",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ccead6",
        "primary-fixed-dim": "#b0cdbb",
        "on-primary-fixed": "#062014",
        "on-primary-fixed-variant": "#324c3e",
        "secondary-fixed": "#ffdfa0",
        "secondary-fixed-dim": "#f6be39",
        "on-secondary-fixed": "#261a00",
        "on-secondary-fixed-variant": "#5c4300",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#ffb59e",
        "on-tertiary-fixed": "#3a0b00",
        "on-tertiary-fixed-variant": "#733521",
        background: "#fbf9f4",
        "on-background": "#1b1c19",
        "surface-variant": "#e4e2dd",
        // Brand-named aliases used freely throughout components
        "patchouli-deep": "#2D4739",
        "oil-gold": "#D4A017",
        "clay-earth": "#A65D46",
        "bone-wash": "#F9F7F2",
        "ink-green": "#1A2B22",
        "sand-gray": "#E8E4D8",
      },
      fontFamily: {
        display: ["var(--font-playfair)", "Georgia", "serif"],
        body: ["var(--font-jakarta)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600", letterSpacing: "0.05em" }],
        "technical-mono": ["13px", { lineHeight: "20px", fontWeight: "400" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
        leaf: "2rem 0.5rem 0.5rem 0.5rem",
        "leaf-br": "0.5rem 0.5rem 2rem 0.5rem",
      },
      maxWidth: {
        container: "1280px",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
      },
      boxShadow: {
        "elevation-1": "0 8px 20px 0 rgba(45, 71, 57, 0.04)",
        "elevation-2": "0 12px 28px 0 rgba(45, 71, 57, 0.08)",
        "inner-glow": "inset 0 1px 0 0 rgba(255,255,255,0.4)",
      },
      backgroundImage: {
        grain: "url('/images/grain.png')",
      },
    },
  },
  plugins: [],
};
